name: docs
on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6

      - name: Test build
        if: github.event_name == 'pull_request'
        run: uv run --group docs mkdocs build --strict

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: uv run --group docs mkdocs gh-deploy --strict --force
